Create setup-and-run-fit.yml
couchbaselabs/fit-app-deployment pull request #3
Opened 2023-09-08 10:14 UTC by littlefermatlives

2023-09-14 12:22 UTC, Aaliya7516 commented on .github/workflows/setup-and-run-fit.yml
> +      - name: start ${{ vars.PERFORMER }}  performer
here, can we try to pass the performer as parameter?
like 
```
./gradlew buildPerformer --args="-d ../ -i performer -s ${{ vars.PERFORMER }}"
docker run --network=fit -d -p 8060:8060 performer
```

2023-09-14 12:24 UTC, Aaliya7516 commented on .github/workflows/setup-and-run-fit.yml
> +          # make
maybe, we can remove this line, if not needed

2023-09-14 12:26 UTC, Aaliya7516 commented on .github/workflows/setup-and-run-fit.yml
> +          cat FITConfiguration.json
we can remove cat command from here.

2023-09-14 12:27 UTC, Aaliya7516 commented on .github/workflows/setup-and-run-fit.yml
> +          sleep 10;
can we try to run sleep command without `;` here?

2023-09-14 18:20 UTC, brett19 requested changes

2023-09-14 18:20 UTC, brett19 commented on .github/workflows/setup-and-run-fit.yml
> +          sleep 10;
We can probably use `docker exec` along with `pg_isready` to directly wait for Postgres to be available, rather than sleeping for an arbitrary period.

2023-09-15 05:54 UTC, littlefermatlives commented on .github/workflows/setup-and-run-fit.yml
> +          sleep 10;
okay @brett19

2023-09-15 05:55 UTC, littlefermatlives commented on .github/workflows/setup-and-run-fit.yml
> +          cat FITConfiguration.json
I think we should keep the cat command to verify if the FITconfiguration.json is correct?

2023-09-20 09:08 UTC, Couch-Matt requested changes

2023-09-20 09:08 UTC, Couch-Matt commented on .github/workflows/setup-and-run-fit.yml
> +          # mvn clean install -Dmaven.test.skip
We do not need this line, this will try to run the tests without the proper parameters passed in the next line

2023-09-20 09:08 UTC, Couch-Matt commented on .github/workflows/setup-and-run-fit.yml
> +      - name: Create postgres perf db
Why are we creating a database? Is the end goal not to end up in the production database here instead:
https://performance-sdk.couchbase.com:8080/situationalRuns

2023-09-20 11:04 UTC, littlefermatlives commented on .github/workflows/setup-and-run-fit.yml
> +      - name: Create postgres perf db
I got this from steps mentioned in SITUATIONAL_TESTING.md. 
```
# below line to create perf network:
docker network create -d bridge perf
docker run -d --restart=always -p 5432:5432 -e POSTGRES_PASSWORD=password --network perf --name timedb timescale/timescaledb:latest-pg14
sleep 10;
docker exec timedb psql -U postgres -c "CREATE DATABASE perf;"
git clone https://github.com/couchbaselabs/jenkins-sdk
cd jenkins-sdk
./gradlew setupPerfDatabase
```
I was not aware of the production database. I need to connect with will to grasp it better.

2023-09-20 11:05 UTC, littlefermatlives commented on .github/workflows/setup-and-run-fit.yml
> +          # mvn clean install -Dmaven.test.skip
Sure, i'll remove this line.

2023-09-20 16:50 UTC, Couch-Matt approved these changes
LGTM, pending automation passing

2023-09-21 06:10 UTC, brett19 approved these changes

2023-09-21 06:23 UTC, merged